site_name: Dark Souls Texture Studio
site_description: Documentation for Dark Souls Texture Studio

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Home: index.md

  - Getting Started:
    - Installation: installation.md
    - Building from source: building.md

  - User Guide:
    - Introduction: introduction.md
    - Settings: settings.md
    - Exporting Textures: exporting.md
    - Replacing Textures: replacing.md
    - Adding Custom Atlases/Icons: custom-icons.md
    - Creating a Custom File: custom-files.md
    - High Resolution Textures: high-resolution.md
    - Merging with Delta Patcher: deltapatch.md
  
  - Supported Games: supported-games.md

  - Other Features: features.md

  - Troubleshooting: troubleshooting.md

  - Advanced:
    - cli: cli.md
    - Console: console.md

  - Contact Me: contact.md